services: 
  # add secret injection via vault
  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    expose:
      - "9092"
      - "9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'p8fFEbKGQ22B6M_Da_vCBw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - kafka

  kafka-consumer:
    build:
      context: .
      dockerfile: KafkaConsumer/Dockerfile
    container_name: kafka-consumer
    depends_on:
      - kafka
      - postgres
      - redis
      - fraud-engine
    environment:
      - Kafka__Topic=Transactions-Topic
      - Kafka__BootstrapServers=kafka:29092
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=transactions;Username=myuser;Password=mypassword
      - ConnectionStrings__Redis=redis:6379
    restart: unless-stopped
    networks:
      - db
      - kafka
    


  postgres:
    image: postgres:16 
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data named volume
      #- ./postgres/init-db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d transactions"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped # Auto restart unless stopped
    networks:
      - db

  redis:
    image: redis:7 
    container_name: redis_cache
    networks:
      - db


  #pgadmin:
  # image: dpage/pgadmin4
  #  container_name: pgadmin_container
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@example.com
  #    PGADMIN_DEFAULT_PASSWORD: your_password
  #  ports:
  #    - "9000:80"
    # Ensure pgAdmin can connect to the 'postgres' service name defined here
  #  depends_on:
  #    - postgres
      
  #kafka-ui:
  #  image: provectuslabs/kafka-ui:latest
  #  container_name: kafka_ui
  #  ports:
  #    - "9001:8080"
  #  environment:
  #    KAFKA_CLUSTERS_0_NAME: local
  #    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
  #  restart: unless-stopped

  fraud-engine:
    build:
      context: .
      dockerfile: FraudEngineService/Dockerfile
    container_name: FraudEngineService
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Redis=redis:6379
    restart: unless-stopped
    networks:
      - proxybackend
      - db

  mock-data-producer:
    build:
      context: .
      dockerfile: MockDataProducer/Dockerfile
    container_name: MockDataProducer
    depends_on:
      - postgres
      - redis
      - kafka
    env_file:
      - .env
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__Redis=redis:6379
      - Kafka__Topic=Transactions-Topic
      - Kafka__BootstrapServers=kafka:29092
    restart: unless-stopped 
    #ports:
    networks:
      - proxybackend
      - kafka

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 80:8080
    networks:
      - proxybackend

  keycloak-postgres:
    image: postgres:16.2
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_KEYCLOAK_DB}
      POSTGRES_USER: ${POSTGRES_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
    expose:
      - "5432"
    volumes:
      - keycloak-postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_KEYCLOAK_USER} -d ${POSTGRES_KEYCLOAK_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: ["start", "--import-realm", "--db=postgres"]
    env_file:
      - .env
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_PROPERTIES: ""
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/${POSTGRES_KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - proxybackend
      - keycloak_network
    volumes:
      - ./.keycloak:/opt/keycloak/data/import:ro

networks:
  keycloak_network:
    driver: bridge
  proxybackend:
    name: proxybackend
    driver: bridge
  db:
   name: db
   driver: bridge
  kafka:
    name: kafka
    driver: bridge
volumes:
  postgres_data: # Define the named volume
  keycloak-postgres_data:
    driver: local

